	top u0 (
		.clk_clk                       (<connected-to-clk_clk>),                       //            clk.clk
		.dut_hip_ctrl_test_in          (<connected-to-dut_hip_ctrl_test_in>),          //   dut_hip_ctrl.test_in
		.dut_hip_ctrl_simu_mode_pipe   (<connected-to-dut_hip_ctrl_simu_mode_pipe>),   //               .simu_mode_pipe
		.dut_hip_pipe_sim_pipe_pclk_in (<connected-to-dut_hip_pipe_sim_pipe_pclk_in>), //   dut_hip_pipe.sim_pipe_pclk_in
		.dut_hip_pipe_sim_pipe_rate    (<connected-to-dut_hip_pipe_sim_pipe_rate>),    //               .sim_pipe_rate
		.dut_hip_pipe_sim_ltssmstate   (<connected-to-dut_hip_pipe_sim_ltssmstate>),   //               .sim_ltssmstate
		.dut_hip_pipe_eidleinfersel0   (<connected-to-dut_hip_pipe_eidleinfersel0>),   //               .eidleinfersel0
		.dut_hip_pipe_eidleinfersel1   (<connected-to-dut_hip_pipe_eidleinfersel1>),   //               .eidleinfersel1
		.dut_hip_pipe_eidleinfersel2   (<connected-to-dut_hip_pipe_eidleinfersel2>),   //               .eidleinfersel2
		.dut_hip_pipe_eidleinfersel3   (<connected-to-dut_hip_pipe_eidleinfersel3>),   //               .eidleinfersel3
		.dut_hip_pipe_powerdown0       (<connected-to-dut_hip_pipe_powerdown0>),       //               .powerdown0
		.dut_hip_pipe_powerdown1       (<connected-to-dut_hip_pipe_powerdown1>),       //               .powerdown1
		.dut_hip_pipe_powerdown2       (<connected-to-dut_hip_pipe_powerdown2>),       //               .powerdown2
		.dut_hip_pipe_powerdown3       (<connected-to-dut_hip_pipe_powerdown3>),       //               .powerdown3
		.dut_hip_pipe_rxpolarity0      (<connected-to-dut_hip_pipe_rxpolarity0>),      //               .rxpolarity0
		.dut_hip_pipe_rxpolarity1      (<connected-to-dut_hip_pipe_rxpolarity1>),      //               .rxpolarity1
		.dut_hip_pipe_rxpolarity2      (<connected-to-dut_hip_pipe_rxpolarity2>),      //               .rxpolarity2
		.dut_hip_pipe_rxpolarity3      (<connected-to-dut_hip_pipe_rxpolarity3>),      //               .rxpolarity3
		.dut_hip_pipe_txcompl0         (<connected-to-dut_hip_pipe_txcompl0>),         //               .txcompl0
		.dut_hip_pipe_txcompl1         (<connected-to-dut_hip_pipe_txcompl1>),         //               .txcompl1
		.dut_hip_pipe_txcompl2         (<connected-to-dut_hip_pipe_txcompl2>),         //               .txcompl2
		.dut_hip_pipe_txcompl3         (<connected-to-dut_hip_pipe_txcompl3>),         //               .txcompl3
		.dut_hip_pipe_txdata0          (<connected-to-dut_hip_pipe_txdata0>),          //               .txdata0
		.dut_hip_pipe_txdata1          (<connected-to-dut_hip_pipe_txdata1>),          //               .txdata1
		.dut_hip_pipe_txdata2          (<connected-to-dut_hip_pipe_txdata2>),          //               .txdata2
		.dut_hip_pipe_txdata3          (<connected-to-dut_hip_pipe_txdata3>),          //               .txdata3
		.dut_hip_pipe_txdatak0         (<connected-to-dut_hip_pipe_txdatak0>),         //               .txdatak0
		.dut_hip_pipe_txdatak1         (<connected-to-dut_hip_pipe_txdatak1>),         //               .txdatak1
		.dut_hip_pipe_txdatak2         (<connected-to-dut_hip_pipe_txdatak2>),         //               .txdatak2
		.dut_hip_pipe_txdatak3         (<connected-to-dut_hip_pipe_txdatak3>),         //               .txdatak3
		.dut_hip_pipe_txdetectrx0      (<connected-to-dut_hip_pipe_txdetectrx0>),      //               .txdetectrx0
		.dut_hip_pipe_txdetectrx1      (<connected-to-dut_hip_pipe_txdetectrx1>),      //               .txdetectrx1
		.dut_hip_pipe_txdetectrx2      (<connected-to-dut_hip_pipe_txdetectrx2>),      //               .txdetectrx2
		.dut_hip_pipe_txdetectrx3      (<connected-to-dut_hip_pipe_txdetectrx3>),      //               .txdetectrx3
		.dut_hip_pipe_txelecidle0      (<connected-to-dut_hip_pipe_txelecidle0>),      //               .txelecidle0
		.dut_hip_pipe_txelecidle1      (<connected-to-dut_hip_pipe_txelecidle1>),      //               .txelecidle1
		.dut_hip_pipe_txelecidle2      (<connected-to-dut_hip_pipe_txelecidle2>),      //               .txelecidle2
		.dut_hip_pipe_txelecidle3      (<connected-to-dut_hip_pipe_txelecidle3>),      //               .txelecidle3
		.dut_hip_pipe_txswing0         (<connected-to-dut_hip_pipe_txswing0>),         //               .txswing0
		.dut_hip_pipe_txswing1         (<connected-to-dut_hip_pipe_txswing1>),         //               .txswing1
		.dut_hip_pipe_txswing2         (<connected-to-dut_hip_pipe_txswing2>),         //               .txswing2
		.dut_hip_pipe_txswing3         (<connected-to-dut_hip_pipe_txswing3>),         //               .txswing3
		.dut_hip_pipe_txmargin0        (<connected-to-dut_hip_pipe_txmargin0>),        //               .txmargin0
		.dut_hip_pipe_txmargin1        (<connected-to-dut_hip_pipe_txmargin1>),        //               .txmargin1
		.dut_hip_pipe_txmargin2        (<connected-to-dut_hip_pipe_txmargin2>),        //               .txmargin2
		.dut_hip_pipe_txmargin3        (<connected-to-dut_hip_pipe_txmargin3>),        //               .txmargin3
		.dut_hip_pipe_txdeemph0        (<connected-to-dut_hip_pipe_txdeemph0>),        //               .txdeemph0
		.dut_hip_pipe_txdeemph1        (<connected-to-dut_hip_pipe_txdeemph1>),        //               .txdeemph1
		.dut_hip_pipe_txdeemph2        (<connected-to-dut_hip_pipe_txdeemph2>),        //               .txdeemph2
		.dut_hip_pipe_txdeemph3        (<connected-to-dut_hip_pipe_txdeemph3>),        //               .txdeemph3
		.dut_hip_pipe_phystatus0       (<connected-to-dut_hip_pipe_phystatus0>),       //               .phystatus0
		.dut_hip_pipe_phystatus1       (<connected-to-dut_hip_pipe_phystatus1>),       //               .phystatus1
		.dut_hip_pipe_phystatus2       (<connected-to-dut_hip_pipe_phystatus2>),       //               .phystatus2
		.dut_hip_pipe_phystatus3       (<connected-to-dut_hip_pipe_phystatus3>),       //               .phystatus3
		.dut_hip_pipe_rxdata0          (<connected-to-dut_hip_pipe_rxdata0>),          //               .rxdata0
		.dut_hip_pipe_rxdata1          (<connected-to-dut_hip_pipe_rxdata1>),          //               .rxdata1
		.dut_hip_pipe_rxdata2          (<connected-to-dut_hip_pipe_rxdata2>),          //               .rxdata2
		.dut_hip_pipe_rxdata3          (<connected-to-dut_hip_pipe_rxdata3>),          //               .rxdata3
		.dut_hip_pipe_rxdatak0         (<connected-to-dut_hip_pipe_rxdatak0>),         //               .rxdatak0
		.dut_hip_pipe_rxdatak1         (<connected-to-dut_hip_pipe_rxdatak1>),         //               .rxdatak1
		.dut_hip_pipe_rxdatak2         (<connected-to-dut_hip_pipe_rxdatak2>),         //               .rxdatak2
		.dut_hip_pipe_rxdatak3         (<connected-to-dut_hip_pipe_rxdatak3>),         //               .rxdatak3
		.dut_hip_pipe_rxelecidle0      (<connected-to-dut_hip_pipe_rxelecidle0>),      //               .rxelecidle0
		.dut_hip_pipe_rxelecidle1      (<connected-to-dut_hip_pipe_rxelecidle1>),      //               .rxelecidle1
		.dut_hip_pipe_rxelecidle2      (<connected-to-dut_hip_pipe_rxelecidle2>),      //               .rxelecidle2
		.dut_hip_pipe_rxelecidle3      (<connected-to-dut_hip_pipe_rxelecidle3>),      //               .rxelecidle3
		.dut_hip_pipe_rxstatus0        (<connected-to-dut_hip_pipe_rxstatus0>),        //               .rxstatus0
		.dut_hip_pipe_rxstatus1        (<connected-to-dut_hip_pipe_rxstatus1>),        //               .rxstatus1
		.dut_hip_pipe_rxstatus2        (<connected-to-dut_hip_pipe_rxstatus2>),        //               .rxstatus2
		.dut_hip_pipe_rxstatus3        (<connected-to-dut_hip_pipe_rxstatus3>),        //               .rxstatus3
		.dut_hip_pipe_rxvalid0         (<connected-to-dut_hip_pipe_rxvalid0>),         //               .rxvalid0
		.dut_hip_pipe_rxvalid1         (<connected-to-dut_hip_pipe_rxvalid1>),         //               .rxvalid1
		.dut_hip_pipe_rxvalid2         (<connected-to-dut_hip_pipe_rxvalid2>),         //               .rxvalid2
		.dut_hip_pipe_rxvalid3         (<connected-to-dut_hip_pipe_rxvalid3>),         //               .rxvalid3
		.dut_hip_serial_rx_in0         (<connected-to-dut_hip_serial_rx_in0>),         // dut_hip_serial.rx_in0
		.dut_hip_serial_rx_in1         (<connected-to-dut_hip_serial_rx_in1>),         //               .rx_in1
		.dut_hip_serial_rx_in2         (<connected-to-dut_hip_serial_rx_in2>),         //               .rx_in2
		.dut_hip_serial_rx_in3         (<connected-to-dut_hip_serial_rx_in3>),         //               .rx_in3
		.dut_hip_serial_tx_out0        (<connected-to-dut_hip_serial_tx_out0>),        //               .tx_out0
		.dut_hip_serial_tx_out1        (<connected-to-dut_hip_serial_tx_out1>),        //               .tx_out1
		.dut_hip_serial_tx_out2        (<connected-to-dut_hip_serial_tx_out2>),        //               .tx_out2
		.dut_hip_serial_tx_out3        (<connected-to-dut_hip_serial_tx_out3>),        //               .tx_out3
		.dut_npor_npor                 (<connected-to-dut_npor_npor>),                 //       dut_npor.npor
		.dut_npor_pin_perst            (<connected-to-dut_npor_pin_perst>),            //               .pin_perst
		.dut_refclk_clk                (<connected-to-dut_refclk_clk>),                //     dut_refclk.clk
		.pld_clk_clk                   (<connected-to-pld_clk_clk>),                   //        pld_clk.clk
		.reset_reset_n                 (<connected-to-reset_reset_n>),                 //          reset.reset_n
		.status_hip_derr_cor_ext_rcv   (<connected-to-status_hip_derr_cor_ext_rcv>),   //     status_hip.derr_cor_ext_rcv
		.status_hip_derr_cor_ext_rpl   (<connected-to-status_hip_derr_cor_ext_rpl>),   //               .derr_cor_ext_rpl
		.status_hip_derr_rpl           (<connected-to-status_hip_derr_rpl>),           //               .derr_rpl
		.status_hip_dlup_exit          (<connected-to-status_hip_dlup_exit>),          //               .dlup_exit
		.status_hip_ev128ns            (<connected-to-status_hip_ev128ns>),            //               .ev128ns
		.status_hip_ev1us              (<connected-to-status_hip_ev1us>),              //               .ev1us
		.status_hip_hotrst_exit        (<connected-to-status_hip_hotrst_exit>),        //               .hotrst_exit
		.status_hip_int_status         (<connected-to-status_hip_int_status>),         //               .int_status
		.status_hip_l2_exit            (<connected-to-status_hip_l2_exit>),            //               .l2_exit
		.status_hip_lane_act           (<connected-to-status_hip_lane_act>),           //               .lane_act
		.status_hip_ltssmstate         (<connected-to-status_hip_ltssmstate>),         //               .ltssmstate
		.status_hip_ko_cpl_spc_header  (<connected-to-status_hip_ko_cpl_spc_header>),  //               .ko_cpl_spc_header
		.status_hip_ko_cpl_spc_data    (<connected-to-status_hip_ko_cpl_spc_data>),    //               .ko_cpl_spc_data
		.tl_cfg_tl_cfg_add             (<connected-to-tl_cfg_tl_cfg_add>),             //         tl_cfg.tl_cfg_add
		.tl_cfg_tl_cfg_ctl             (<connected-to-tl_cfg_tl_cfg_ctl>),             //               .tl_cfg_ctl
		.tl_cfg_tl_cfg_sts             (<connected-to-tl_cfg_tl_cfg_sts>)              //               .tl_cfg_sts
	);

