	top u0 (
		.clk_clk                           (<connected-to-clk_clk>),                           //                 clk.clk
		.ddr_sfp_side_signal_export        (<connected-to-ddr_sfp_side_signal_export>),        // ddr_sfp_side_signal.export
		.dp_switch_export                  (<connected-to-dp_switch_export>),                  //           dp_switch.export
		.hip_ctrl_test_in                  (<connected-to-hip_ctrl_test_in>),                  //            hip_ctrl.test_in
		.hip_ctrl_simu_mode_pipe           (<connected-to-hip_ctrl_simu_mode_pipe>),           //                    .simu_mode_pipe
		.hip_pipe_sim_pipe_pclk_in         (<connected-to-hip_pipe_sim_pipe_pclk_in>),         //            hip_pipe.sim_pipe_pclk_in
		.hip_pipe_sim_pipe_rate            (<connected-to-hip_pipe_sim_pipe_rate>),            //                    .sim_pipe_rate
		.hip_pipe_sim_ltssmstate           (<connected-to-hip_pipe_sim_ltssmstate>),           //                    .sim_ltssmstate
		.hip_pipe_eidleinfersel0           (<connected-to-hip_pipe_eidleinfersel0>),           //                    .eidleinfersel0
		.hip_pipe_eidleinfersel1           (<connected-to-hip_pipe_eidleinfersel1>),           //                    .eidleinfersel1
		.hip_pipe_eidleinfersel2           (<connected-to-hip_pipe_eidleinfersel2>),           //                    .eidleinfersel2
		.hip_pipe_eidleinfersel3           (<connected-to-hip_pipe_eidleinfersel3>),           //                    .eidleinfersel3
		.hip_pipe_powerdown0               (<connected-to-hip_pipe_powerdown0>),               //                    .powerdown0
		.hip_pipe_powerdown1               (<connected-to-hip_pipe_powerdown1>),               //                    .powerdown1
		.hip_pipe_powerdown2               (<connected-to-hip_pipe_powerdown2>),               //                    .powerdown2
		.hip_pipe_powerdown3               (<connected-to-hip_pipe_powerdown3>),               //                    .powerdown3
		.hip_pipe_rxpolarity0              (<connected-to-hip_pipe_rxpolarity0>),              //                    .rxpolarity0
		.hip_pipe_rxpolarity1              (<connected-to-hip_pipe_rxpolarity1>),              //                    .rxpolarity1
		.hip_pipe_rxpolarity2              (<connected-to-hip_pipe_rxpolarity2>),              //                    .rxpolarity2
		.hip_pipe_rxpolarity3              (<connected-to-hip_pipe_rxpolarity3>),              //                    .rxpolarity3
		.hip_pipe_txcompl0                 (<connected-to-hip_pipe_txcompl0>),                 //                    .txcompl0
		.hip_pipe_txcompl1                 (<connected-to-hip_pipe_txcompl1>),                 //                    .txcompl1
		.hip_pipe_txcompl2                 (<connected-to-hip_pipe_txcompl2>),                 //                    .txcompl2
		.hip_pipe_txcompl3                 (<connected-to-hip_pipe_txcompl3>),                 //                    .txcompl3
		.hip_pipe_txdata0                  (<connected-to-hip_pipe_txdata0>),                  //                    .txdata0
		.hip_pipe_txdata1                  (<connected-to-hip_pipe_txdata1>),                  //                    .txdata1
		.hip_pipe_txdata2                  (<connected-to-hip_pipe_txdata2>),                  //                    .txdata2
		.hip_pipe_txdata3                  (<connected-to-hip_pipe_txdata3>),                  //                    .txdata3
		.hip_pipe_txdatak0                 (<connected-to-hip_pipe_txdatak0>),                 //                    .txdatak0
		.hip_pipe_txdatak1                 (<connected-to-hip_pipe_txdatak1>),                 //                    .txdatak1
		.hip_pipe_txdatak2                 (<connected-to-hip_pipe_txdatak2>),                 //                    .txdatak2
		.hip_pipe_txdatak3                 (<connected-to-hip_pipe_txdatak3>),                 //                    .txdatak3
		.hip_pipe_txdetectrx0              (<connected-to-hip_pipe_txdetectrx0>),              //                    .txdetectrx0
		.hip_pipe_txdetectrx1              (<connected-to-hip_pipe_txdetectrx1>),              //                    .txdetectrx1
		.hip_pipe_txdetectrx2              (<connected-to-hip_pipe_txdetectrx2>),              //                    .txdetectrx2
		.hip_pipe_txdetectrx3              (<connected-to-hip_pipe_txdetectrx3>),              //                    .txdetectrx3
		.hip_pipe_txelecidle0              (<connected-to-hip_pipe_txelecidle0>),              //                    .txelecidle0
		.hip_pipe_txelecidle1              (<connected-to-hip_pipe_txelecidle1>),              //                    .txelecidle1
		.hip_pipe_txelecidle2              (<connected-to-hip_pipe_txelecidle2>),              //                    .txelecidle2
		.hip_pipe_txelecidle3              (<connected-to-hip_pipe_txelecidle3>),              //                    .txelecidle3
		.hip_pipe_txdeemph0                (<connected-to-hip_pipe_txdeemph0>),                //                    .txdeemph0
		.hip_pipe_txdeemph1                (<connected-to-hip_pipe_txdeemph1>),                //                    .txdeemph1
		.hip_pipe_txdeemph2                (<connected-to-hip_pipe_txdeemph2>),                //                    .txdeemph2
		.hip_pipe_txdeemph3                (<connected-to-hip_pipe_txdeemph3>),                //                    .txdeemph3
		.hip_pipe_txmargin0                (<connected-to-hip_pipe_txmargin0>),                //                    .txmargin0
		.hip_pipe_txmargin1                (<connected-to-hip_pipe_txmargin1>),                //                    .txmargin1
		.hip_pipe_txmargin2                (<connected-to-hip_pipe_txmargin2>),                //                    .txmargin2
		.hip_pipe_txmargin3                (<connected-to-hip_pipe_txmargin3>),                //                    .txmargin3
		.hip_pipe_txswing0                 (<connected-to-hip_pipe_txswing0>),                 //                    .txswing0
		.hip_pipe_txswing1                 (<connected-to-hip_pipe_txswing1>),                 //                    .txswing1
		.hip_pipe_txswing2                 (<connected-to-hip_pipe_txswing2>),                 //                    .txswing2
		.hip_pipe_txswing3                 (<connected-to-hip_pipe_txswing3>),                 //                    .txswing3
		.hip_pipe_phystatus0               (<connected-to-hip_pipe_phystatus0>),               //                    .phystatus0
		.hip_pipe_phystatus1               (<connected-to-hip_pipe_phystatus1>),               //                    .phystatus1
		.hip_pipe_phystatus2               (<connected-to-hip_pipe_phystatus2>),               //                    .phystatus2
		.hip_pipe_phystatus3               (<connected-to-hip_pipe_phystatus3>),               //                    .phystatus3
		.hip_pipe_rxdata0                  (<connected-to-hip_pipe_rxdata0>),                  //                    .rxdata0
		.hip_pipe_rxdata1                  (<connected-to-hip_pipe_rxdata1>),                  //                    .rxdata1
		.hip_pipe_rxdata2                  (<connected-to-hip_pipe_rxdata2>),                  //                    .rxdata2
		.hip_pipe_rxdata3                  (<connected-to-hip_pipe_rxdata3>),                  //                    .rxdata3
		.hip_pipe_rxdatak0                 (<connected-to-hip_pipe_rxdatak0>),                 //                    .rxdatak0
		.hip_pipe_rxdatak1                 (<connected-to-hip_pipe_rxdatak1>),                 //                    .rxdatak1
		.hip_pipe_rxdatak2                 (<connected-to-hip_pipe_rxdatak2>),                 //                    .rxdatak2
		.hip_pipe_rxdatak3                 (<connected-to-hip_pipe_rxdatak3>),                 //                    .rxdatak3
		.hip_pipe_rxelecidle0              (<connected-to-hip_pipe_rxelecidle0>),              //                    .rxelecidle0
		.hip_pipe_rxelecidle1              (<connected-to-hip_pipe_rxelecidle1>),              //                    .rxelecidle1
		.hip_pipe_rxelecidle2              (<connected-to-hip_pipe_rxelecidle2>),              //                    .rxelecidle2
		.hip_pipe_rxelecidle3              (<connected-to-hip_pipe_rxelecidle3>),              //                    .rxelecidle3
		.hip_pipe_rxstatus0                (<connected-to-hip_pipe_rxstatus0>),                //                    .rxstatus0
		.hip_pipe_rxstatus1                (<connected-to-hip_pipe_rxstatus1>),                //                    .rxstatus1
		.hip_pipe_rxstatus2                (<connected-to-hip_pipe_rxstatus2>),                //                    .rxstatus2
		.hip_pipe_rxstatus3                (<connected-to-hip_pipe_rxstatus3>),                //                    .rxstatus3
		.hip_pipe_rxvalid0                 (<connected-to-hip_pipe_rxvalid0>),                 //                    .rxvalid0
		.hip_pipe_rxvalid1                 (<connected-to-hip_pipe_rxvalid1>),                 //                    .rxvalid1
		.hip_pipe_rxvalid2                 (<connected-to-hip_pipe_rxvalid2>),                 //                    .rxvalid2
		.hip_pipe_rxvalid3                 (<connected-to-hip_pipe_rxvalid3>),                 //                    .rxvalid3
		.hip_serial_rx_in0                 (<connected-to-hip_serial_rx_in0>),                 //          hip_serial.rx_in0
		.hip_serial_rx_in1                 (<connected-to-hip_serial_rx_in1>),                 //                    .rx_in1
		.hip_serial_rx_in2                 (<connected-to-hip_serial_rx_in2>),                 //                    .rx_in2
		.hip_serial_rx_in3                 (<connected-to-hip_serial_rx_in3>),                 //                    .rx_in3
		.hip_serial_tx_out0                (<connected-to-hip_serial_tx_out0>),                //                    .tx_out0
		.hip_serial_tx_out1                (<connected-to-hip_serial_tx_out1>),                //                    .tx_out1
		.hip_serial_tx_out2                (<connected-to-hip_serial_tx_out2>),                //                    .tx_out2
		.hip_serial_tx_out3                (<connected-to-hip_serial_tx_out3>),                //                    .tx_out3
		.led_wire_export                   (<connected-to-led_wire_export>),                   //            led_wire.export
		.pcie_256_hip_lock_fixedclk_locked (<connected-to-pcie_256_hip_lock_fixedclk_locked>), //   pcie_256_hip_lock.fixedclk_locked
		.pcie_nrst_npor                    (<connected-to-pcie_nrst_npor>),                    //           pcie_nrst.npor
		.pcie_nrst_pin_perst               (<connected-to-pcie_nrst_pin_perst>),               //                    .pin_perst
		.pcie_refclk_clk                   (<connected-to-pcie_refclk_clk>),                   //         pcie_refclk.clk
		.reset_reset_n                     (<connected-to-reset_reset_n>)                      //               reset.reset_n
	);

